export const GET_FREELANCES_LOAD = "GET_FREELANCES_LOAD"
export const GET_FREELANCES_FAIL = "GET_FREELANCES_FAIL"
export const GET_FREELANCES_SUCCESS = "GET_FREELANCES_SUCCESS"
export const GET_FREELANCE = "GET_FREELANCE"

export const TOGGLE_FALSE = "TOGGLE_FALSE"
export const TOGGLE_TRUE = "TOGGLE_TRUE"